export const GET_INFO_REQUEST = 'GET_INFO_REQUEST';
export const GET_INFO_SUCCESS = 'GET_INFO_SUCCESS';
export const CHANGE_NAME_REQUEST = 'CHANGE_NAME_REQUEST';
export const CHANGE_NAME_SUCCESS = 'CHANGE_NAME_SUCCESS';
export const ERROR_HANDLER = 'ERROR_HANDLER';
